.github/release.config.js, .github/workflows/main.yml, packages/vsce/package.json
=> allow independent versioning

.github/release.config.js, .github/workflows/changelog.yml, .github/workflows/main.yml, packages/vsce/README.md
Finally release a patch for all CICS clients for Zowe V1 LTS
Download the artifacts in the existing GitHub release (v4.0.9)
🤞🏽
=> Final publish of V1

.github/workflows/main.yml, package.json, scripts/bundleTgz.js
Fix offline bundling of the CLI `.tgz` file
Run `npm run package` and check the `cics-cli.tgz#package.json#dependencies` and the sdk should have a dependency number instead of a `file:../dist/path.tgz`
Related to:
- https://github.com/zowe/zowe-cli-standalone-package/pull/252
=> Fix CLI tgz bundle

.github/workflows/main.yml
This one will publish the SDK, and may fail to publish the CLI
Then we should be able to rerun the workflow  (with current) to publish the CLI)
=> update workflow for V2

.prettierignore, .vscode/extension.json, .vscode/settings.json, package-lock.json, packages/vsce/CHANGELOG.md, packages/vsce/src/utils/getIconPath.ts, prettier.config.js
- fixes #112
1. `npm i`
2. `npm run build`
3. Run the debugger and you should see icons now 😋 
=> fix(icons-v1): Display icons for all resources

.prettierignore, .vscode/extension.json, .vscode/settings.json, package-lock.json, packages/vsce/CHANGELOG.md, packages/vsce/src/utils/profileManagement.ts, packages/vsce/src/utils/profileUtils.ts, prettier.config.js
- fixes #112
1. `npm i`
2. `npm run build`
3. Run the debugger and you should see icons now 😋 
=> fix(icons): Display icons for all resources

package-lock.json, package.json, packages/cli/CHANGELOG.md, packages/sdk/CHANGELOG.md, packages/vsce/CHANGELOG.md, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedLibraryTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedLocalFileTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedPipelineTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedProgramTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedTCPIPServiceTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedTaskTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedTransactionTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedURIMapTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedWebServiceTree.ts, packages/vsce/src/utils/webviewHTML.ts
Fixed several identified problems with possible null values in the tree and web views
=> Fix code issues v3

package-lock.json, packages/vsce/CHANGELOG.md, packages/vsce/src/trees/CICSCombinedLocalFileTree.ts, packages/vsce/src/trees/CICSCombinedProgramTree.ts, packages/vsce/src/trees/CICSCombinedTransactionTree.ts, packages/vsce/src/utils/webviewHTML.ts
Fixed several identified problems with possible null values in the tree and web views
=> Fix code issues v1

.npmrc
Updates the npmrc file to use the `npm-release` registry on V1, which should fix publishing and have V1 use the same registry as V2 and V3
=> Update npmrc to have correct Zowe registry

packages/vsce/CHANGELOG.md, packages/vsce/src/extension.ts
Displays the old `Zowe Explorer was modified for the CICS Extension.` in the log instead of in a popup.
Package and install extension, and when opening ZE should not show popup anymore.
=> Log during activation instead of showing popup

.github/workflows/auto-comment.yml, .github/workflows/codeql.yml, .github/workflows/stale.yml, package-lock.json, packages/vsce/CHANGELOG.md, packages/vsce/src/extension.ts
Include updates from `2.3.6` to not display the information message that CICS modified Zowe Explorer
Update workflows that have changed in main since the next branch was cut
=> Update next with main

.github/workflows/auto-comment.yml, .github/workflows/main.yml, .github/workflows/update-project.yml
Update workflow permissions for v1
=> Update workflow permissions (v1)

.github/release.config.js, packages/cli/CHANGELOG.md, packages/sdk/CHANGELOG.md, packages/vsce/CHANGELOG.md
Only release plugin CLI and SDK as 6.0.0 to public zowe.jfrog
=> chore: update release config to get cli/sdk with a non prerelease

.github/release.config.js
This PR will update the latest tag to match the same version as `zowe-v3-lts` going forward.
This PR should be merged only after the Zowe v3.0 announcement 😋 
**Note:** This PR shall be merged with the `release-current` label.
Also, this is dependent on the `@zowe/zowe-explorer-api@zowe-v3-lts`
=> chore: update workflows in preparation for Zowe v3 GA

packages/vsce/README.md
Addresses https://github.com/zowe/cics-for-zowe-client/issues/155
URLs to resources from this repository have been updated to include the full file path.
Build and package the extension, and confirm that the URLs to screenshots and other resources work properly.
=> Fully specify urls for repo files in VSCE README

packages/vsce/CHANGELOG.md, packages/vsce/src/trees/CICSTree.ts
It does a correct condition checking on whether or not Team Configuration File exists.
- click on + icon 
- Click on "Create a New CICS Profile"
- zowe.config.json file opens up
- Currently, these changes only take care of the condition when a Team Configuration file is available globally.
- Still investigating the case when Team Configuration file is missing,
=> Correcting condition to read team configuration file.

packages/vsce/CHANGELOG.md, packages/vsce/tsup.config.json
The PR https://github.com/zowe/cics-for-zowe-client/pull/165 marks SSH2 as an external dependency for tsup. This breaks the CICS extension - reverting for now.
Created the vsix package, which I then installed and tested manually.
Resolves #174
=> Fixing issue in 3.1.0 due to SSH2 external dep.

packages/sdk/CHANGELOG.md, packages/sdk/__tests__/__unit__/get/Get.resource.unit.test.ts, packages/sdk/__tests__/__unit__/utils/Utils.unit.test.ts, packages/sdk/src/constants/CicsCmci.constants.ts, packages/sdk/src/doc/IGetResourceUriOptions.ts, packages/sdk/src/doc/IResourceParms.ts, packages/sdk/src/doc/IResourceQueryParms.ts, packages/sdk/src/methods/get/Get.ts, packages/sdk/src/utils/Utils.ts
Allows a user to specify query parameters to be added to the CMCI query URI (SUMMONLY, NODISCARD, OVERRIDEWARNINGCOUNT) by adding an optional addition to the supplied params.
This will allow the VSCE to retrieve a cache token from CMCI which will enable pagination on large result sets.
=> Add CMCI query parameters to SDK getResource

packages/sdk/CHANGELOG.md, packages/sdk/__tests__/__unit__/cache/Cache.unit.test.ts, packages/sdk/__tests__/__unit__/utils/Utils.unit.test.ts, packages/sdk/src/constants/CicsCmci.constants.ts, packages/sdk/src/doc/ICacheParms.ts, packages/sdk/src/doc/IResultCacheParms.ts, packages/sdk/src/doc/index.ts, packages/sdk/src/methods/cache/Cache.ts, packages/sdk/src/methods/cache/index.ts, packages/sdk/src/utils/Utils.ts
Requires #171 - Merged!
Resolves zowe/cics-for-zowe-client#169
Adds getCache method to the SDK to retrieve a cached result from CMCI using a cache token returned by getResource.
This will allow the VSCE to paginate large result sets using the SDK rather than axios HTTP requests.
=> Add SDK getCache method

packages/vsce/CHANGELOG.md, packages/vsce/package.json, packages/vsce/src/commands/showParameterCommand.ts, packages/vsce/src/trees/CICSRegionTree.ts
Currently the "Show SIT Parameters" menu option can be selected on inactive regions which will cause an error. I've changed this so that this option is greyed out when the region is inactive. I've also added a check in the command so that the error does not surface when executed from the command palette.
Connected to a plex with both active and inactive regions and verified that the menu item for 'Show SIT Parameters' is grayed out when the region is inactive. This will also be the case if multi-select is used and includes an inactive region.
Resolves https://github.com/zowe/cics-for-zowe-client/issues/167
=> Remove the sit param menu option when a region is inactive

.github/release.config.js, package-lock.json, packages/cli/package.json, scripts/bundleTgz.js
Removes the SDK as bundled dependency of the CLI. It will be temporarily restored when `npm run package` is run to create an offline TGZ.
1. `cd` into the CLI package folder
1. Run `npm pack` and confirm no deps are bundled
1. Run `npm run package` and confirm that deps are bundled
This should be published as `release-patch` since release was skipped for the last V2 PR:
https://github.com/zowe/cics-for-zowe-client/actions/runs/12603902416/job/35130057064
=> [v2] Remove bundled deps and update release config

packages/vsce/CHANGELOG.md, packages/vsce/src/extension.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedLibraryTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedLocalFileTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedPipelineTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedProgramTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedTCPIPServiceTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedTaskTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedTransactionTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedURIMapTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedWebServiceTree.ts, packages/vsce/src/trees/CICSLibraryTree.ts, packages/vsce/src/trees/CICSLocalFileTree.ts, packages/vsce/src/trees/CICSProgramTree.ts, packages/vsce/src/trees/CICSRegionsContainer.ts, packages/vsce/src/trees/CICSTaskTree.ts, packages/vsce/src/trees/CICSTransactionTree.ts, packages/vsce/src/trees/CICSWebTree.ts, packages/vsce/src/trees/treeItems/CICSLibraryTreeItem.ts, packages/vsce/src/trees/treeItems/web/CICSPipelineTree.ts, packages/vsce/src/trees/treeItems/web/CICSTCPIPServiceTree.ts, packages/vsce/src/trees/treeItems/web/CICSURIMapTree.ts, packages/vsce/src/trees/treeItems/web/CICSWebServiceTree.ts, packages/vsce/src/utils/expansionHandler.ts, packages/vsce/src/utils/profileUtils.ts
Resolves #194 
Updates the Regions container tree icon when auto-expanded by the Plex tree expanding.
=> update regions icon when auto-expanded

packages/vsce/CHANGELOG.md, packages/vsce/src/utils/commandUtils.ts, packages/vsce/src/utils/profileManagement.ts
Fixes using a profile without a plex specified that only has 1 plex available - it was trying to loop an array when the response was actually an object.
Follow on fix for #178
=> handle getCache returning non-array

packages/vsce/src/commands/disableCommands/index.ts, packages/vsce/src/commands/enableCommands/index.ts, packages/vsce/src/commands/index.ts, packages/vsce/src/extension.ts
Refactor `extension.ts` to reduce repetition. The majority of the expansion events were 1 of 2 methods, with a couple of exceptions. The refactor ensures the common behaviour share a single method.
I also moved the commands registration out of the file to it's own method for tidiness.
=> Refactor command registration and tree expansion events

packages/vsce/CHANGELOG.md, packages/vsce/src/utils/profileManagement.ts
Resolves #200 
Adds a check for a NODATA response when generating a cache token for the combined trees. If the query comes back with NODATA, an error is thrown by the SDK. This was not handled and ignored by the VSCE.
=> Catch NODATA response when generating cache

packages/vsce/CHANGELOG.md, packages/vsce/src/trees/treeItems/CICSLibraryTreeItem.ts
Resolves #212 .
This changes the LibraryTreeItems to use a default filter of their Library name so only the Library datasets in that Library show up in that tree. Then it appends the active filter of the library to that filter to search the DSName attribute. 
Resulting behaviour is only the library datasets with the correct library name show up under that tree, with the filter applying to the dsname attribute.
Have multiple Library resources with different datasets in. Expand each library. Before this update, they would show the same datasets - now they should show correct datasets. 
Updated view with bug fixed.
=> show library datasets under correct library name

packages/sdk/__tests__/__mocks__/CmciGetResponse.ts, packages/sdk/__tests__/__mocks__/nodata.xml, packages/sdk/__tests__/__mocks__/ok.1_record.xml, packages/sdk/__tests__/__mocks__/ok.2_records.xml, packages/sdk/__tests__/__mocks__/ok.cache.xml, packages/sdk/__tests__/__unit__/get/Get.resource.unit.test.ts
Adapts SDK unit tests to use real CMCI responses for a more accurate behaviour.
=> Using real data for unit test mocking

packages/vsce/CHANGELOG.md, packages/vsce/package.json, packages/vsce/src/trees/CICSTree.ts
Resolves #222 
Removes multi-select
Simplifies profile selection code so edit and delete profile match
Behaviour now in line with Zowe Explorer
=> remove multi-select, simplify profile selection code

packages/vsce/__tests__/__unit__/trees/CICSLibraryTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSLocalFileTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSPlexTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSProgramTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSRegionTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSRegionsContainer.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSSessionTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSTaskTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSTransactionTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSWebTree.unit.test.ts, packages/vsce/__tests__/__utils__/globalMocks.ts
=> Unit test for cics trees

packages/sdk/CHANGELOG.md, packages/sdk/__tests__/__mocks__/CmciGetResponse.ts, packages/sdk/__tests__/__unit__/CicsCmciRestClient.unit.test.ts, packages/sdk/__tests__/__unit__/cache/Cache.unit.test.ts, packages/sdk/__tests__/__unit__/get/Get.resource.unit.test.ts, packages/sdk/src/constants/CicsCmci.constants.ts, packages/sdk/src/doc/ICMCIRequestOptions.ts, packages/sdk/src/doc/index.ts, packages/sdk/src/methods/cache/Cache.ts, packages/sdk/src/methods/get/Get.ts, packages/sdk/src/rest/CicsCmciRestClient.ts, packages/sdk/src/rest/CicsCmciRestError.ts, packages/sdk/src/rest/index.ts, packages/vsce/CHANGELOG.md, packages/vsce/src/trees/CICSPlexTree.ts, packages/vsce/src/utils/expansionHandler.ts, packages/vsce/src/utils/profileManagement.ts
Adds a failOnNodata flag, defaulting to true (which is the current behaviour), to dictate if CMCI sending a NODATA response should throw an error or not.
* PR relies on #204 
=> SDK getResource failOnNoData flag

packages/vsce/CHANGELOG.md, packages/vsce/__tests__/__unit__/utils/plexUtils.unit.test.ts, packages/vsce/src/utils/plexUtils.ts, packages/vsce/src/utils/profileManagement.ts
Filter duplicate cicsplexes so that these do not appear in the tree.
Have added unit tests for the compare function,
This is for defect https://github.com/zowe/cics-for-zowe-client/issues/227.
=> Removed duplicate CICSplexes so they don't appear in the tree

.github/workflows/main.yml, packages/vsce/__tests__/__e2e__/resources/wiremock/__files/ok-cache-plex.xml, packages/vsce/__tests__/__e2e__/resources/wiremock/mappings/ok-cache-plex.json
=> run e2e GUI tests in CI

packages/cli/src/imperative.ts, packages/sdk/src/constants/CICSProfileDefinition.ts, packages/sdk/src/constants/index.ts, packages/vsce/src/utils/profileManagement.ts
Profile definition was repeated for CLI and VSCE. This PR adds a method to the SDK to retrieve the profile definition to use in both.
=> Standardise cics profile definition for CLI and VSCE

.github/workflows/main.yml
Now that we're building the notices on PRs and not on release, we don't want to predicate the release on the notices having happened (because they won't have done...!)
=> Don't require notices for release

.github/workflows/main.yml, packages/vsce/NOTICE
E2E test cases will now run on mac os with Standalone jar. 
To execute it in local `npm run test:e2e` 
=> e2e will run now on mac with wiremock standalone jar

.github/workflows/main.yml, packages/vsce/NOTICE
We've had an issue with PRs not running the release step of the workflow. We're hoping adding in this manual trigger will allow it to be rerun if necessary.
=> release on manual workflows

.github/workflows/main.yml
Runs the NOTICE file updates as part of the release, pushing to the main branch after the PR is merged - the same behaviour as dep version and changelog updates.
I ran the steps as part of another stage to test the generation and commiting worked as expected - it did. 
There is no way to 100% guarantee this runs as part of the release but I am confident. We will watch carefully on the next release to ensure it works okay.
=> Run notice updates on release

packages/sdk/CHANGELOG.md, packages/sdk/src/constants/CicsCmci.constants.ts, packages/sdk/src/doc/ICICSExtenderConfig.ts, packages/sdk/src/doc/index.ts, packages/vsce/CHANGELOG.md, packages/vsce/__tests__/__unit__/extending/CICSExtenderApiConfig.unit.test.ts, packages/vsce/src/extending/CICSExtenderApiConfig.ts, packages/vsce/src/extension.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedPipelineTree.ts, packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedWebServiceTree.ts, packages/vsce/src/trees/CICSPipelineTree.ts, packages/vsce/src/trees/CICSWebServiceTree.ts
Add an extender API that can return some configuration for the extension.
Performed manual testing + added a unit test. 
=> Add extender API that return select config

packages/cli/CHANGELOG.md, packages/cli/__tests__/__unit__/define/bundle/Bundle.definition.unit.test.ts, packages/cli/__tests__/__unit__/define/bundle/Bundle.handler.unit.test.ts, packages/cli/__tests__/__unit__/define/bundle/__snapshots__/Bundle.definition.unit.test.ts.snap, packages/cli/__tests__/__unit__/define/bundle/__snapshots__/Bundle.handler.unit.test.ts.snap, packages/cli/src/-strings-/en.ts, packages/cli/src/define/Define.definition.ts, packages/cli/src/define/bundle/Bundle.definition.ts, packages/cli/src/define/bundle/Bundle.handler.ts, packages/sdk/CHANGELOG.md, packages/sdk/__tests__/__unit__/CicsCmciRestClient.unit.test.ts, packages/sdk/__tests__/__unit__/CicsProfileDefinition.unit.test.ts, packages/sdk/__tests__/__unit__/define/Define.bundle.unit.test.ts, packages/sdk/src/constants/CicsCmci.constants.ts, packages/sdk/src/doc/IBundleParms.ts, packages/sdk/src/doc/index.ts, packages/sdk/src/methods/define/Define.ts
Resolves #72 
Adds `zowe cics define bundle` as CLI option with SDK method, as requested by the community.
=> Add Bundle as option of CLI Define

packages/vsce/package.json, packages/vsce/src/commands/index.ts, packages/vsce/src/commands/inspectResourceCommand.ts, packages/vsce/src/commands/resourceInspectorViewCommand.ts, packages/vsce/src/constants/CICS.messages.ts, packages/vsce/src/extending/CICSExtenderApiConfig.ts, packages/vsce/src/extension.ts, packages/vsce/src/model/SupportedResources.ts, packages/vsce/src/model/index.ts, packages/vsce/src/trees/ResourceInspectorViewProvider.ts
This is a command to launch resource inspector by just providing the name of the resource and the type, although currently this is set to hidden.
Manually tested to make sure this integration point works.
=> Initial command to launching resource inspector by resource name and resource type

packages/vsce/package.json, packages/vsce/src/commands/resourceInspectorViewCommand.ts
- Instills Command palette support Resource Inspector
- Declares a command before using it : `cics-extension-for-zowe.inspectResource`
=> Command Palette support for RI

package-lock.json, package.json, packages/vsce/src/utils/profileManagement.ts
- Updates the `brace-expansion` dependency in package-lock
- Updates the `glob` dependency to not depend on vulnerable package `inflight` in `yamljs`
- Fixes inconsistent use of optional chaining identified by a SAST tool
Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>Signed-off-by: Andrew W. Harn <andrew.harn@broadcom.com>
=> Fix inconsistent optional chaining and update dependencies (v2)

packages/vsce/__tests__/__unit__/commands/inspectResourceCommandUtils.test.ts, packages/vsce/src/commands/filterResourceCommands.ts, packages/vsce/src/commands/inspectResourceCommandUtils.ts, packages/vsce/src/constants/CICS.messages.ts, packages/vsce/src/doc/meta/IResourceMeta.ts, packages/vsce/src/doc/meta/bundle.meta.ts, packages/vsce/src/doc/meta/bundlePart.meta.ts, packages/vsce/src/doc/meta/library.meta.ts, packages/vsce/src/doc/meta/libraryDataset.meta.ts, packages/vsce/src/doc/meta/localFile.meta.ts, packages/vsce/src/doc/meta/pipeline.meta.ts, packages/vsce/src/doc/meta/program.meta.ts, packages/vsce/src/doc/meta/task.meta.ts, packages/vsce/src/doc/meta/tcpip.meta.ts, packages/vsce/src/doc/meta/transaction.meta.ts, packages/vsce/src/doc/meta/urimap.meta.ts, packages/vsce/src/doc/meta/webservice.meta.ts, packages/vsce/src/trees/CICSRegionTree.ts, packages/vsce/src/trees/ResourceInspectorViewProvider.ts, packages/vsce/src/webviews/resource-inspector-panel/ResourceInspector.tsx
The new (but unreleased!) Resource Inspector uses the CMCI names for resources (CICSLocalFile etc) in the view itself and also in the command palette to open the view.
It's a nicer UX to call them "Local File" etc.
Resolves https://github.com/zowe/cics-for-zowe-client/issues/387
=> use human readable names for resource types

packages/vsce-api/__tests__/__unit__/interfaces.test.ts, packages/vsce-api/src/getAPI.ts, packages/vsce-api/src/interfaces/IResourceAction.ts, packages/vsce-api/src/interfaces/IResourceContext.ts, packages/vsce-api/src/interfaces/IResourceExtender.ts, packages/vsce/src/commands/openLocalFileCommand.ts, packages/vsce/src/extending/CICSResourceExtender.ts, packages/vsce/src/resources/actions/LocalFileActions.ts, packages/vsce/src/resources/actions/ProgramActions.ts, packages/vsce/src/resources/actions/index.ts, packages/vsce/src/trees/ResourceInspectorViewProvider.ts, packages/vsce/src/webviews/common/vscode.ts, packages/vsce/src/webviews/resource-inspector-panel/ResourceInspector.tsx
Adds a resourceExtender class to our API (not yet exposed) to allow actions to be registered against resource types. This will allow us to offer a set of available actions to perform on views like Resource Inspector.
An example would be registering a NewCopy action against CICSPrograms.
=> Adds resourceExtender to allow actions registered on resources

packages/vsce/CHANGELOG.md, packages/vsce/__tests__/__unit__/doc/meta.library.test.ts, packages/vsce/__tests__/__unit__/doc/meta.librarydataset.test.ts, packages/vsce/src/commands/inspectResourceCommandUtils.ts, packages/vsce/src/doc/meta/IResourceMeta.ts, packages/vsce/src/doc/meta/bundlePart.meta.ts, packages/vsce/src/doc/meta/libraryDataset.meta.ts, packages/vsce/src/doc/meta/task.meta.ts, packages/vsce/src/doc/meta/transaction.meta.ts, packages/vsce/src/doc/meta/webservice.meta.ts
Stores the maxium primary key length in the meta file for each resource, if it's not the default value of 8, to be used to validate users' inputs when inspecting resources in the command palette.
This will allow new resources to have custom lengths rather than being restricted to 8
https://github.com/user-attachments/assets/ca5094ef-f21d-4d09-a463-bb2e8ff53e66
=> Store maximum resource length in meta files for validation

packages/vsce/__tests__/__unit__/trees/CICSPlexTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSRegionTree.unit.test.ts, packages/vsce/__tests__/__unit__/trees/CICSTree.unit.test.ts, packages/vsce/__tests__/__unit__/utils/PersistentStorage.unit.test.ts, packages/vsce/__tests__/__unit__/utils/lastUsedRegionUtils.unit.test.ts, packages/vsce/src/commands/getFilterPlexResources.ts, packages/vsce/src/doc/meta/IResourceMeta.ts, packages/vsce/src/doc/meta/JVMServer.meta.ts, packages/vsce/src/doc/meta/bundle.meta.ts, packages/vsce/src/doc/meta/bundlePart.meta.ts, packages/vsce/src/doc/meta/library.meta.ts, packages/vsce/src/doc/meta/libraryDataset.meta.ts, packages/vsce/src/doc/meta/localFile.meta.ts, packages/vsce/src/doc/meta/pipeline.meta.ts, packages/vsce/src/doc/meta/program.meta.ts, packages/vsce/src/doc/meta/task.meta.ts, packages/vsce/src/doc/meta/tcpip.meta.ts, packages/vsce/src/doc/meta/transaction.meta.ts, packages/vsce/src/doc/meta/urimap.meta.ts, packages/vsce/src/doc/meta/webservice.meta.ts, packages/vsce/src/resources/ResourceContainer.ts, packages/vsce/src/trees/CICSResourceContainerNode.ts, packages/vsce/src/trees/CICSTree.ts, packages/vsce/src/utils/PersistentStorage.ts, packages/vsce/src/utils/lastUsedRegionUtils.ts
Genericises the PersistentStorage class methods to prevent having a set of 4 methods for EACH resource type.
Also converts to a singleton to prevent instantiating it in each file we use it.
This, in turn, allows you to inspect CICSLibraryDatasetName and CICSBundlePart resources from the command palette, as it adds them to the list of supported resources. This builds on top of the PR to validate those input lengths.
=> Refactor PersistentStorage to reduce repeated code

packages/vsce/CHANGELOG.md, packages/vsce/src/webviews/resource-inspector-panel/Contextmenu.tsx, packages/vsce/src/webviews/resource-inspector-panel/ResourceInspector.tsx
Removes RI Action div for the resource types which does not have any extended actions.
=> Removal of RI Actions for unsupported Resources
