package-lock.json
package.json

This should fix the release workflow

lock lerna version

---

package.json
packages/cli/package.json
packages/sdk/package.json
scripts/bundleTgz.js
scripts/rewriteShrinkwrap.js

add scope to publishConfig

---

.github/release.config.js

This is just to publish the 1.3.6 to OVSX 😋

add vsix dir for OVSX publishing

---

.github/workflows/main.yml
packages/cli/package.json

This should make the CI/CD and manual/local publishing of all packages in this monorepo
You may try `npm publish --dry-run` or just wait for the next vNext release

test: Add an NPM shwrinkwrap file to the CLI plug-in

---

package-lock.json
packages/vsce/CHANGELOG.md
packages/vsce/package.json

Updave VSCE version

---

.github/workflows/audit.yml
.github/workflows/changelog.yml
.github/workflows/codeql.yml
.github/workflows/linter.yml
.prettierignore
.vscode/extension.json
.vscode/settings.json
package-lock.json
package.json
packages/vsce/CHANGELOG.md
packages/vsce/src/utils/profileManagement.ts
packages/vsce/src/utils/profileUtils.ts
prettier.config.js

- fixes #112
1. `npm i`
2. `npm run build`
3. Run the debugger and you should see icons now 😋 

fix(icons-v3): Display icons for all resources

---

.github/workflows/main.yml
package-lock.json
package.json
packages/cli/CHANGELOG.md
packages/cli/__tests__/__snapshots__/imperative.test.ts.snap
packages/cli/package.json
packages/cli/src/imperative.ts
packages/sdk/CHANGELOG.md
packages/sdk/package.json
packages/vsce/package.json

Upgrades dependencies to their latest available versions
Increases the Node engine version to 18.12.0
Removes unused dependencies

Implement cleanup

---

package-lock.json
packages/vsce/CHANGELOG.md
packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedLibraryTree.ts
packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedLocalFileTree.ts
packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedPipelineTree.ts
packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedProgramTree.ts
packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedTCPIPServiceTree.ts
packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedTaskTree.ts
packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedTransactionTree.ts
packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedURIMapTree.ts
packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedWebServiceTree.ts
packages/vsce/src/utils/webviewHTML.ts

Fixed several identified problems with possible null values in the tree and web views

Fix forward null issues (v2)

---

.github/workflows/auto-comment.yml
.github/workflows/codeql.yml

Update commenter workflow to use same workflow as other Zowe repositories
Update CodeQL workflow to v3

Replace comment workflow and update CodeQL

---

package-lock.json
package.json
packages/cli/__tests__/__resources__/properties/example_properties.yaml
packages/cli/__tests__/__system__/add-to-list/csdGroup/__snapshots__/cli.add-to-list.csdGroup.system.test.ts.snap
packages/cli/__tests__/__system__/define/program/__snapshots__/cli.define.program.system.test.ts.snap
packages/cli/__tests__/__system__/define/transaction/__snapshots__/cli.define.transaction.system.test.ts.snap
packages/cli/__tests__/__system__/define/urimap-client/__snapshots__/cli.define.urimap.client.system.test.ts.snap
packages/cli/__tests__/__system__/define/urimap-pipeline/__snapshots__/cli.define.urimap.pipeline.system.test.ts.snap
packages/cli/__tests__/__system__/define/urimap-server/__snapshots__/cli.define.urimap.server.system.test.ts.snap
packages/cli/__tests__/__system__/define/webservice/__snapshots__/cli.define.webservice.system.test.ts.snap
packages/cli/__tests__/__system__/delete/program/__snapshots__/cli.delete.program.system.test.ts.snap
packages/cli/__tests__/__system__/delete/transaction/__snapshots__/cli.delete.transaction.system.test.ts.snap
packages/cli/__tests__/__system__/delete/urimap/__snapshots__/cli.delete.urimap.system.test.ts.snap
packages/cli/__tests__/__system__/delete/webservice/__snapshots__/cli.delete.webservice.system.test.ts.snap
packages/cli/__tests__/__system__/disable/urimap/__snapshots__/cli.disable.urimap.system.test.ts.snap
packages/cli/__tests__/__system__/discard/program/__snapshots__/cli.discard.program.system.test.ts.snap
packages/cli/__tests__/__system__/discard/transaction/__snapshots__/cli.discard.transaction.system.test.ts.snap
packages/cli/__tests__/__system__/discard/urimap/__snapshots__/cli.discard.urimap.system.test.ts.snap
packages/cli/__tests__/__system__/enable/urimap/__snapshots__/cli.enable.urimap.system.test.ts.snap
packages/cli/__tests__/__system__/get/resource/__snapshots__/cli.get.resource.system.test.ts.snap
packages/cli/__tests__/__system__/install/program/__snapshots__/cli.install.program.system.test.ts.snap
packages/cli/__tests__/__system__/install/transaction/__snapshots__/cli.install.transaction.system.test.ts.snap
packages/cli/__tests__/__system__/install/urimap/__snapshots__/cli.install.urimap.system.test.ts.snap
packages/cli/__tests__/__system__/refresh/program/__snapshots__/cli.refresh.program.system.test.ts.snap
packages/cli/__tests__/__system__/remove-from-list/csdGroup/__snapshots__/cli.remove-from-list.csdGroup.system.test.ts.snap

Update cli-test-utils and snapshots for system tests

---

.github/workflows/audit.yml

Allows the main branch audit badge to work by enabling nightly audit runs

Restore nightly audit

---

CONTRIBUTING.md

Updates the contributing guidelines link to the Imperative wiki.

Update Imperative wiki link

---

.github/workflows/auto-comment.yml
.github/workflows/main.yml
.github/workflows/update-project.yml

Update workflow permissions (v2)

---

.github/release.config.js
package.json
packages/cli/CHANGELOG.md
packages/sdk/CHANGELOG.md
packages/vsce/CHANGELOG.md

Fix workspaces definition for cics monorepo

---

.github/workflows/audit.yml
.github/workflows/changelog.yml
.github/workflows/codeql.yml
.github/workflows/linter.yml

Update workflows to allow them to run on the `zowe-v?-lts` branch

chore: update workflows to support zowe-v?-lts branches

---

package-lock.json
packages/vsce/package.json

Update vsce dependency to use `@vscode/vsce` and use latest 2.x version

Update vsce version to latest 2.x and use newer vscode scoped package

---

package-lock.json
package.json
packages/vsce/package.json

Clean all warnings reported by npm-audit
- Run `npm audit` 
```
found 0 vulnerabilities
```

chore: clean npm-audit report

---

package-lock.json
package.json
packages/cli/CHANGELOG.md
packages/sdk/CHANGELOG.md
packages/vsce/CHANGELOG.md
packages/vsce/package.json

Updates a few dependencies for technical currency
- Run `npm audit` 😋 
**After #234**
```
found 0 vulnerabilities
```
**Before #234**
```
esbuild  <=0.24.2
Severity: moderate
esbuild enables any website to send any requests to the development server and read the response - https://github.com/advisories/GHSA-67mh-4wv8-2f99
fix available via `npm audit fix --force`
Will install tsup@2.0.3, which is a breaking change
node_modules/esbuild
tsup  >=2.1.0
Depends on vulnerable versions of esbuild
packages/vsce/node_modules/tsup
xml2js  <0.5.0
Severity: moderate
xml2js is vulnerable to prototype pollution - https://github.com/advisories/GHSA-776f-qx25-q3cc
fix available via `npm audit fix --force` …
```

chore: update dependencies :yum:

---

packages/vsce/src/trees/CICSCombinedTrees/CICSCombinedLocalFileTree.ts
packages/vsce/src/trees/CICSLocalFileTree.ts

Would like to use constants where possible so this is just a bit of minor cleanup.

Minor cleanup to use constants

---

packages/vsce/src/trees/CICSPipelineTree.ts
packages/vsce/src/trees/CICSTCPIPServiceTree.ts
packages/vsce/src/trees/CICSURIMapTree.ts
packages/vsce/src/trees/CICSWebServiceTree.ts
packages/vsce/src/utils/CICSLogger.ts

Added some additional debug logging
Ran unit tests and also manual walk through.

Added some more logging

---

package-lock.json

[v3] Update dev deps for technical currency

---

packages/vsce/__tests__/__unit__/trees/CICSRegionsContainer.unit.test.ts
packages/vsce/src/commands/clearResourceFilterCommand.ts
packages/vsce/src/commands/showLogsCommand.ts

Resolves
https://github.com/zowe/cics-for-zowe-client/security/code-scanning/108
https://github.com/zowe/cics-for-zowe-client/security/code-scanning/118
https://github.com/zowe/cics-for-zowe-client/security/code-scanning/39

remove unused code

---

packages/cli/__tests__/__snapshots__/imperative.test.ts.snap
packages/sdk/CHANGELOG.md
packages/sdk/src/constants/CICSProfileDefinition.ts

https://github.com/zowe/cics-for-zowe-client/issues/291
I upgraded from the existing version to the version with the schema successfully. I then upgraded to a new version of the schema that had an additional parameter in.

Add schema version for CICS schema

---

packages/vsce/package.json
packages/vsce/src/commands/inspectResourceCommand.ts
packages/vsce/src/commands/resourceInspectorViewCommand.ts

Renamed command and ran manual test to make sure it works as expected.
Manual test.

Rename command so that prefix is consistant with other commands

---

package-lock.json
packages/cli/__tests__/__system__/add-to-list/csdGroup/cli.add-to-list.csdGroup.system.test.ts
packages/cli/__tests__/__system__/define/urimap-client/cli.define.urimap.client.system.test.ts
packages/cli/__tests__/__system__/define/urimap-pipeline/cli.define.urimap.pipeline.system.test.ts
packages/cli/__tests__/__system__/define/urimap-server/cli.define.urimap.server.system.test.ts
packages/cli/__tests__/__system__/enable/urimap/cli.enable.urimap.system.test.ts
packages/cli/__tests__/__system__/install/urimap/cli.install.urimap.system.test.ts
packages/sdk/__tests__/__unit__/get/Get.resource.unit.test.ts
packages/sdk/src/constants/CicsCmci.constants.ts
packages/sdk/src/doc/ICMCIResponseResultSummary.ts
packages/sdk/src/doc/ICacheParms.ts
packages/sdk/src/doc/IResourceParms.ts
packages/sdk/src/doc/IResourceQueryParms.ts
packages/sdk/src/doc/IResultCacheParms.ts
packages/sdk/src/doc/index.ts
packages/sdk/src/methods/cache/Cache.ts
packages/sdk/src/methods/cache/index.ts
packages/sdk/src/methods/get/Get.ts
packages/sdk/src/utils/Utils.ts
packages/sdk/src/utils/index.ts
packages/vsce/CHANGELOG.md
packages/vsce/package.json
packages/vsce/src/commands/clearResourceFilterCommand.ts
packages/vsce/src/utils/profileManagement.ts

I believe this is the preferred way of removing axios from the V2 LRS branch since this does not add any enhancements 🙏  
I will need some help testing these changes since I'm still recovering my environments from a few other destructive tests I was doing.

Axios: Remove it without adding enhancements :yum:

---

packages/cli/README.md

Remove reference to old `zowe profiles` command

Update CLI readme

---

packages/vsce/package.json
packages/vsce/src/commands/inspectResourceCommand.ts
packages/vsce/src/commands/inspectResourceCommandUtils.ts
packages/vsce/src/constants/CICS.defaults.ts
packages/vsce/src/constants/CICS.messages.ts

Added command to launch the resource inspector view from the command palette.
Manually tested.

Added resource inspector command to the command palette

---

.github/workflows/main.yml

Removes second e2e test run. Now same behaviour as unit testing

Remove e2e duplicate run

---

packages/vsce/__tests__/__unit__/utils/lastUsedRegionUtils.unit.test.ts
packages/vsce/src/commands/setCICSRegionCommand.ts
packages/vsce/src/utils/lastUsedRegionUtils.ts

fixed bugs for lastUsedRegion [issue](https://github.com/zowe/cics-for-zowe-client/issues/393)

fixed tree closing on quickpick

---

.github/workflows/sonar.yml
.vscode/settings.json
sonar-project.properties

Enables Sonarqube.
Working towards https://github.com/zowe/cics-for-zowe-client/issues/87

Enable sonarqube

---

.github/workflows/main.yml
package-lock.json
package.json

Update workflow to add Node 24 to the matrix
Update a dev dependency to work with Node 24

Update dev dependency and workflow for Node 24

---

.github/workflows/main.yml
package-lock.json
package.json
packages/sdk/CHANGELOG.md
packages/sdk/src/rest/CicsCmciRestClient.ts

Update use of `isString` to support Node 24.
Add Node 24 workflow
Update dev dependency to support use of Node 24.

Update dev dependency and workflows to add Node 24.

---

packages/vsce/__tests__/__e2e__/playwright.config.ts
packages/vsce/__tests__/__e2e__/specs/commands.spec.ts
packages/vsce/__tests__/__e2e__/specs/jvmEndpoint.spec.ts
packages/vsce/__tests__/__e2e__/specs/jvmServer.spec.ts
packages/vsce/__tests__/__e2e__/specs/profiles.spec.ts
packages/vsce/__tests__/__e2e__/specs/program.spec.ts
packages/vsce/__tests__/__e2e__/specs/resourceInspector.spec.ts
packages/vsce/__tests__/__e2e__/utils/helpers.ts
packages/vsce/__tests__/__unit__/doc/meta.jvmendpoint.test.ts
packages/vsce/__tests__/__unit__/doc/meta.jvmserver.test.ts
packages/vsce/__tests__/__unit__/utils/PersistentStorage.unit.test.ts
packages/vsce/src/commands/disableCommands/disableJVMServerCommand.ts
packages/vsce/src/commands/enableCommands/enableJVMServerCommand.ts
packages/vsce/src/commands/showLibraryCommand.ts
packages/vsce/src/doc/meta/JVMServer.meta.ts
packages/vsce/src/doc/resources/IJVMServer.ts
packages/vsce/src/trees/ResourceInspectorUtils.ts
packages/vsce/src/utils/treeUtils.ts

Add missing license headers
